<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Guias de remessa</h3>
            </div>
            <div class="panel-body">
                <form method="GET" action="<?=$this->url('guiasderemessa', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-6 col-sm-5" style="padding-bottom: 10px">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar guias" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Número</th>
                        <th>Exercício</th>
                        <th>Data de criação</th>
                        <th>Emissor</th>
                        <th>Posto de Destino</th>
                        <th>Quantidade de processos</th>
                        <th style="min-width: 100px;">&nbsp;</th>
                    </tr>
                    <? foreach ($this->guias as $guia): ?>
                        <tr>
                            <td class="col-sd-2"><?= $guia->getNumero() ?></td>            
                            <td><?= $guia->getAnoExercicio() ?></td>            
                            <td><?= $guia->getDataCriacao()->format('d/m/Y') ?></td>            
                            <td><?= $guia->getEmissor()->getNome() ?></td>            
                            <td><?= $guia->getPostoDeTrabalho() ?></td>                     
                            <td><?= $guia->getQtdProcessos() ?></td>                     
                            <td>
                                <a class="btn btn-xs btn-info" href="/guiasderemessa/visualizar/<?=$guia->getIdGuiaDeRemessa() ?>" title="Vizualizar">
                                    <span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-success" href="/guiasderemessa/receber/<?=$guia->getIdGuiaDeRemessa() ?>" title="Receber">
                                    <span class="glyphicon glyphicon-thumbs-up"></span></a>
                                <a class="btn btn-xs btn-danger" href="/guiasderemessa/rejeitar/<?=$guia->getIdGuiaDeRemessa() ?>" title="Rejeitar">
                                    <span class="glyphicon glyphicon-thumbs-down"></span></a></td>                     
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->guias,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Secretarias'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'guiasderemessa',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
</div>