<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Secretarias</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('orgaosexternos', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Novo orgão externo</a>
                </div>
                <form method="GET" action="<?=$this->url('orgaosexternos', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar orgão externo" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Abreviacao</th>
                        <th>Nome</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->orgaosExternos as $key => $orgaoexterno): ?>
                        <tr>
                            <td class="col-sd-2"><?= $orgaoexterno->getSigla() ?></td>            
                            <td><?= $orgaoexterno->getNome() ?></td>            
                            <td class="col-sd-2">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/orgaosexternos/visualizar/<?=$orgaoexterno->getIdOrgaoExterno()?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/orgaosexternos/editar/<?=$orgaoexterno->getIdOrgaoExterno()?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/orgaosexternos/excluir/<?=$orgaoexterno->getIdOrgaoExterno()?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->orgaosExternos,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'OrgaosExternos'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'orgaosexternos',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>