<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Application\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idUsuario', 'matricula', 'digitoMatricula', 'nome', 'email', 'senha', 'dataCriacao', 'ativo', 'funcao', 'setores', 'guiasDeRemessaEnviadas', 'processos', 'pendencias', 'pareceres');
        }

        return array('__isInitialized__', 'idUsuario', 'matricula', 'digitoMatricula', 'nome', 'email', 'senha', 'dataCriacao', 'ativo', 'funcao', 'setores', 'guiasDeRemessaEnviadas', 'processos', 'pendencias', 'pareceres');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricula', array());

        return parent::getMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function getDigito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDigito', array());

        return parent::getDigito();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function isAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAtivo', array());

        return parent::isAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFuncao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuncao', array());

        return parent::getFuncao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricula($matricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricula', array($matricula));

        return parent::setMatricula($matricula);
    }

    /**
     * {@inheritDoc}
     */
    public function setDigito($digito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDigito', array($digito));

        return parent::setDigito($digito);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCriacao(\DateTime $dataCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array($dataCriacao));

        return parent::setDataCriacao($dataCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFuncao(\Application\Entity\Funcao $funcao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuncao', array($funcao));

        return parent::setFuncao($funcao);
    }

    /**
     * {@inheritDoc}
     */
    public function addGuiaDeRemessaEnviada(\Application\Entity\GuiaDeRemessa $guiaDeRemessa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGuiaDeRemessaEnviada', array($guiaDeRemessa));

        return parent::addGuiaDeRemessaEnviada($guiaDeRemessa);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiaDeRemessaEnviada($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiaDeRemessaEnviada', array($key));

        return parent::getGuiaDeRemessaEnviada($key);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGuiaDeRemessaEnviada($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGuiaDeRemessaEnviada', array($key));

        return parent::removeGuiaDeRemessaEnviada($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuiasDeRemessaEnviadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuiasDeRemessaEnviadas', array());

        return parent::getGuiasDeRemessaEnviadas();
    }

    /**
     * {@inheritDoc}
     */
    public function addProcesso(\Application\Entity\Processo $processo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProcesso', array($processo));

        return parent::addProcesso($processo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesso($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesso', array($key));

        return parent::getProcesso($key);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProcesso($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProcesso', array($key));

        return parent::removeProcesso($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessos', array());

        return parent::getProcessos();
    }

    /**
     * {@inheritDoc}
     */
    public function addSetor(\Application\Entity\Setor $setor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSetor', array($setor));

        return parent::addSetor($setor);
    }

    /**
     * {@inheritDoc}
     */
    public function getSetorAtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSetorAtual', array());

        return parent::getSetorAtual();
    }

    /**
     * {@inheritDoc}
     */
    public function getSetor($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSetor', array($key));

        return parent::getSetor($key);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSetor($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSetor', array($key));

        return parent::removeSetor($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getSetores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSetores', array());

        return parent::getSetores();
    }

    /**
     * {@inheritDoc}
     */
    public function addPendencia(\Application\Entity\Pendencia $pendencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPendencia', array($pendencia));

        return parent::addPendencia($pendencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendencia($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendencia', array($key));

        return parent::getPendencia($key);
    }

    /**
     * {@inheritDoc}
     */
    public function removePendencia($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePendencia', array($key));

        return parent::removePendencia($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendencias', array());

        return parent::getPendencias();
    }

    /**
     * {@inheritDoc}
     */
    public function addParecer(\Application\Entity\Parecer $parecer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParecer', array($parecer));

        return parent::addParecer($parecer);
    }

    /**
     * {@inheritDoc}
     */
    public function getParecer($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParecer', array($key));

        return parent::getParecer($key);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParecer($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParecer', array($key));

        return parent::removeParecer($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getPareceres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPareceres', array());

        return parent::getPareceres();
    }

}
