<div class="row">
    
    <div id='a' class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Menu</h3>
            </div>
            <div class="panel-body">
                <ul class="navbar-link">
                    <li><a href="<?php echo $this->url('assuntos') ?>">Assuntos</a></li>
                    <li><a href="<?php echo $this->url('workflows') ?>">Workflows</a></li>
                </ul>
            </div>
        </div>
    </div>
   
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Workflows</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('workflows', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Novo workflow</a>
                </div>
                <form method="GET" action="<?=$this->url('workflows', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar workflow" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Assunto</th>
                        <th>Descrição</th>
                        <th>Quantidade de postos</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->workflows as $workflow): ?>
                        <tr>          
                            <td class="col-sd-1"><?= $workflow->getAssunto()->getNome(); ?></td>            
                            <td class="col-sd-1"><?= substr($workflow->getDescricao(),0,45)."..." ?></td>            
                            <td class="col-sd-1"><?= count($workflow->getFluxosPostos()) ?></td>            
                            <td class="col-sd-2">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/workflows/visualizar/<?=$workflow->getIdWorkflow()?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <?/*<a class="btn btn-xs btn-warning" title="Editar" href="/workflows/editar/<?=$workflow->getIdWorkflow()?>"><span class="glyphicon glyphicon-edit"></span></a>*/?>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/workflows/excluir/<?=$workflow->getIdWorkflow()?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->workflows,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Assuntos'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'workflows',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
    
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>