<?
if($this->workflow){
    $id = $this->workflow->getIdWorkflow();
    $assunto = $this->workflow->getAssunto()->getNome();
    $descricao = $this->workflow->getDescricao();
}
?>
<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading list-group">
                <h3 class="panel-title">Vizualizar workflow</h3>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Id:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="nomeTxt"><?=$id;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Assunto:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="nomeTxt"><?=$assunto;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Descrição:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="siglaTxt"><?=$descricao;?></p>
                    </div>
                </div>
            </div>
            <?  foreach ($this->workflow->getFluxosPostos() as $key => $posto):?>
            <div class="panel-heading list-group-item">
                <?=$key+1?>º Posto - <?=$posto->getPosto()?>
            </div>
            <div class="panel-body list-group-item">
                <b>Quantidade máxima de dias no posto:</b>
                <?=($posto->getDiasUteis())?$posto->getDiasUteis():"Não existem dias definidos neste posto."?>
            </div>
            <div class="panel-body list-group-item">
                <b>Descrição:</b>
                <?=($posto->getDescricao())?$posto->getDescricao():"Não há descrção definida para este item."?>
            </div>
            <?  endforeach;?>
            <div class="panel-footer center">
                <a href="<?=$this->url('workflows', array('action' => 'index'))?>" class="btn btn-success" title="Voltar"><span class="glyphicon glyphicon-backward"></span>Voltar</a>
            </div>
        </div>
    </div>
</div>