<?
if($this->assunto){
    $id = $this->assunto->getIdAssunto();
    $nome = $this->assunto->getNome();
    $secretaria = $this->assunto->getSetor()->getSecretaria()->getNome();
    $tipoSetor = $this->assunto->getSetor()->getTipoSetor()->getNome();
    $setor = $this->assunto->getSetor()->getNome();
    $descricao = $this->assunto->getDescricao();
}
?>
<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading list-group">
                <h3 class="panel-title">Visualizar assunto</h3>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Id:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="idTxt"><?=$id;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Nome:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="nomeTxt"><?=$nome;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Secretaria responsável:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="secretariaTxt"><?=$secretaria;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Tipo do setor responsável:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="tipoSetorTxt"><?=$tipoSetor;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Setor responsável:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="setorTxt"><?=$setor;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body list-group-item">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Descrição:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="descricaoTxt"><?=$descricao;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <a href="<?=$this->url('assuntos', array('action' => 'index'))?>" class="btn btn-success" title="Voltar"><span class="glyphicon glyphicon-backward"></span>Voltar</a>
            </div>
        </div>
    </div>
</div>