<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Adicionar novo tipo de documento</h3>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('tiposdedocumento', array('action' => 'adicionar')); ?>">
            <div class="panel-body">
                <div class="form-group">
                    <label for="nomeTxt" class="col-lg-3 col-md-3 control-label">Nome:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="nomeTxt" class="form-control" id="nomeTxt" placeholder="Exemplo">
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
        </div>
    </div>
</div>