<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Tipos de documento</h3>
            </div>
            <div class="panel-body">
                <?if($this->sucesso):?>
                    <p>Tipo de documento removido com sucesso!</p>
                <?endif;?>
            </div>
            <div class="panel-footer">
                <a href="<?=$this->url('tiposdedocumento', array('action' => 'index'))?>" class="btn btn-success" title="Voltar"><span class="glyphicon glyphicon-backward"></span>Voltar</a>
            </div>
        </div>
    </div>
</div>