<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Adicionar novo setor</h3>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('setores', array('action' => 'adicionar')); ?>">
            <div class="panel-body">
                <div class="form-group">
                    <label for="secretariaSlct" class="col-lg-3 col-md-3 control-label">Secretaria:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="secretariaSlct" class="form-control" id="secretariaSlct">
                            <option>----Selecione uma secretaria----</option>
                            <?  foreach ($this->secretarias as $secretaria):?>
                            <option value=<?=$secretaria->getIdSecretaria()?>><?=$secretaria->getNome()?></option>
                            <?  endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tipoSlct" class="col-lg-3 col-md-3 control-label">Tipo:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="tipoSlct" class="form-control" id="tipoSlct">
                            <option>----Selecione um tipo de setor----</option>
                            <?  foreach ($this->tiposSetor as $tipoSetor):?>
                            <option value=<?=$tipoSetor->getIdTipoSetor()?>><?=$tipoSetor->getNome()?></option>
                            <?  endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="setorMestreSlct" class="col-lg-3 col-md-3 control-label">Setor mestre:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="setorMestreSlct" class="form-control" id="setorMestreSlct">
                            <option>----Selecione um setor mestre----</option>
                            <?  /*foreach ($this->setores as $setor):?>
                            <option value=<?=$setor->getIdSetor()?>><?=$setor->getNome()?></option>
                            <?  endforeach;*/?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="nomeTxt" class="col-lg-3 col-md-3 control-label">Nome:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="nomeTxt" class="form-control" id="nomeTxt" placeholder="Controle de Exemplos">
                    </div>
                </div>
                <div class="form-group">
                    <label for="siglaTxt" class="col-lg-3 col-md-3 control-label">Sigla:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="siglaTxt" class="form-control" id="siglaTxt" placeholder="CCE">
                    </div>
                </div>
                <div class="form-group">
                    <label for="arquivoRd" class="col-lg-3 col-md-3 control-label">O setor é um arquivo de processos?</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="radio" name="arquivoRd" class="form-inline" id="destinatarioRd" checked="checked" value="0"/> Não&nbsp;
                        <input type="radio" name="arquivoRd" class="form-inline" id="destinatarioRd" value="1"/> Sim
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
        </div>
    </div>
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function(){
    $('#secretariaSlct').change(function(){
        var valor = $(this).val();
        $.post('/setores/getsetorcombobysecretaria',{data: valor},function(ret){
            $('#setorMestreSlct').html(ret);
        });
    });
});
<? $this->headScript()->captureEnd(); ?>