<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Adicionar nova pendencia ao processos <?=$processo?></h3>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('pendencias', array('action' => 'adicionar')); ?>" enctype="multipart/form-data">
                <input type="hidden" name="processoHdn" id="processoHdn" value="<?=$idProcesso?>"/>
            <div class="panel-body">
                <div class="form-group">
                    <label for="imagemFile" class="col-lg-3 col-md-3 control-label">Documento:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="file" name="imagemFile" class="form-control" id="imagemFile"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="descricaoTxt" class="col-lg-3 col-md-3 control-label">Descrição:</label>
                    <div class="col-lg-9 col-md-9">
                        <textarea name="descricaoTxt" class="form-control" id="descricaoTxt" placeholder="O processo carece de exemplos."></textarea>
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
        </div>
    </div>
</div>