<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pendências do processo <?=$numeroProcesso?></h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Descricao</th>
                        <th>Data de criação</th>
                        <th>Resolvido?</th>
                        <th>Data de conclusão</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->pendencias as $pendencia): ?>
                        <tr>
                            <td class="col-sd-1"><?= substr($pendencia->getDescricao(),0,35).'...' ?></td>            
                            <td class="col-sd-1"><?= $pendencia->getDataCriacao()->format('d/m/Y') ?></td>            
                            <td class="col-sd-1"><?= ($pendencia->getResolvido())? 'Sim':'Não';?></td>            
                            <td class="col-sd-2"><?= ($pendencia->getDataConclusao())?
                                                       $pendencia->getDataConclusao():NULL ?></td>            
                            <td class="col-sd-2">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/pendencias/visualizar/<?=$pendencia->getIdPendencia().'?processo='.$idProcesso?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/parecer/adicionar/<?=$pendencia->getIdPendencia()?>"><span class="glyphicon glyphicon-plus"></span></a>
                                <a class="btn btn-xs btn-success" title="Resolver" href="/pendencias/resolver/<?=$pendencia->getIdPendencia().'?processo='.$idProcesso?>"><span class="glyphicon glyphicon-ok"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->pendencias,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Pendecias'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'pendencias',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
    
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>