<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle('SIGEPROC - Sistema de Gerenciamento de Processos')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-ui.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?
                        $home = $this->url('home');
                        $relatorios = $this->url('relatorios');
//                        if($this->layout()->role == 'Administrador'){
                            $assuntos = $this->url('assuntos');
                            $orgaosexternos = $this->url('orgaosexternos');
                            $processos = $this->url('processos');
                            $secretarias = $this->url('secretarias');
                            $setores = $this->url('setores');
                            $usuarios = $this->url('usuarios');
//                        }
                        $logout = $this->url('logout');
                    ?>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo-w.png') ?>" alt="SIGEPROC"/></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?if($this->funcao != 'GUEST'):?>
                        <ul class="nav navbar-nav">
                            <li <?=$this->MenuAtivo($home)?>>
                                <a href="<?=$home?>">Principal</a>
                            </li>
                            <li <?=$this->MenuAtivo($relatorios)?>>
                                <a href="<?=$relatorios?>">Relatórios</a>
                            </li>
                            <?if(($this->funcao == 'Administrador')||($this->funcao == 'root')):?>
                            <li <?=$this->MenuAtivo($assuntos)?>>
                                <a href="<?=$assuntos?>">Assuntos</a>
                            </li>
                            <li <?=$this->MenuAtivo($processos)?>>
                                <a href="<?=$processos?>">Processos</a>
                            </li>
                            <li <?=$this->MenuAtivo($secretarias)?>>
                                <a href="<?=$secretarias?>">Secretarias</a>
                            </li>
                            <li <?=$this->MenuAtivo($setores)?>>
                                <a href="<?=$setores?>">Postos de trabalho</a></li>
<!--                            <li><a href="#">Configurações</a></li>-->
                            <li <?=$this->MenuAtivo($usuarios)?>>
                                <a href="<?=$usuarios?>">Usuários</a>
                            </li>
                            <?endif;?>
                            <li <?=$this->MenuAtivo($logout)?>>
                                <a href="<?=$logout?>">Sair</a>
                            </li>
                        </ul>
                    <?endif;?>
                    <span class="search-bar">
                        <form action="/processos/buscar" method="GET">
                            <input class="search-box default-search" type="text" name="busca" placeholder="Digite o nº do processo/ano" />  
                            <a href="#" onclick="$(this).parent().submit();">
                                <img src="<?php echo $this->basePath('img/busca-transparencia.png') ?>" width="45" height="45">
                            </a>
                        </form>
                    </span>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <?php echo $this->message(); ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> por <a href="mailto:irving.oliveira@gmail.com">Irving Oliveira</a>. SIGEPROC é um software livre licenciado sob a <a href="http://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License</a>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
