<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Secretarias</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('secretarias', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Nova secretaria</a>
                </div>
                <form method="GET" action="<?=$this->url('secretarias', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar secretaria" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Sigla</th>
                        <th>Nome</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->secretarias as $key => $secretaria): ?>
                        <? if ($key % 2 == 0): ?>
                            <tr style="background-color: #f9f9f9">
                            <? else: ?>
                            <tr style="background-color: #d7d7d7">
                            <? endif; ?>
                            <td><?= $secretaria->getSigla() ?></td>            
                            <td><?= $secretaria->getNome() ?></td>            
                            <td>
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/secretarias/vizualizar/<?=$secretaria->getIdSecretaria()?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/secretarias/editar/<?=$secretaria->getIdSecretaria()?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/secretarias/excluir/<?=$secretaria->getIdSecretaria()?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->secretarias,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Secretaria'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'secretarias',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>