<div class="jumbotron">

</div>

<div class="row">
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Processos no setor</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-5 col-md-offset-1">
                    <a href="/guiasderemessa">
                        <p style="font-size: 80pt"><?=$this->processosNoSetor?></p>
                    </a>
                </div>                
                <div class="col-md-5">
                    <p style="padding-top: 25px">Processos estacionados neste setor aguradando por encaminhamento.</p>
                </div>                
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Processos a serem recebidos</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-5 col-md-offset-1">
                    <p style="font-size: 80pt">0</p>
                </div>                
                <div class="col-md-5">
                    <p style="padding-top: 20px">Processos encaminhados para este setor aguardando recebimento.</p>
                </div>                
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Processos em atrazo</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-5 col-md-offset-1">
                    <p style="font-size: 80pt;">0</p>
                </div>                
                <div class="col-md-5">
                    <p style="padding-top: 30px">Processos em atrazo neste setor.</p>
                </div>                
            </div>
        </div>
    </div>

<!--    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

--></div>
