<div class="row">
    
    <div id='a' class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Menu</h3>
            </div>
            <div class="panel-body">
                <ul class="navbar-link">
                    <li><a href="<?php echo $this->url('processos') ?>">Processos</a></li>
                    <li><a href="<?php echo $this->url('tiposdedocumento') ?>">Tipos de documentos</a></li>
                </ul>
            </div>
        </div>
    </div>
   
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Processos</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('processos', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Novo processo</a>
                </div>
                <form method="GET" action="<?=$this->url('processos', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar processo" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Número</th>
                        <th>Ano de exercício</th>
                        <th>Data de abertura</th>
                        <th>Assunto</th>
                        <th>Volumes</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->processos as $processo): ?>
                        <tr>
                            <td class="col-sd-1"><?= $processo->getNumero() ?></td>            
                            <td class="col-sd-1"><?= $processo->getAnoExercicio(); ?></td>            
                            <td class="col-sd-1"><?= $processo->getDataAbertura()->format('d/m/Y'); ?></td>            
                            <td class="col-sd-1"><?= $processo->getAssunto()->getnome(); ?></td>            
                            <td class="col-sd-1"><?= $processo->getVolume(); ?></td>            
                            <td class="col-sd-2">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/processos/visualizar/<?=$processo->getIdProcesso();?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/processos/editar/<?=$processo->getIdProcesso();?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/processos/excluir/<?=$processo->getIdProcesso();?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->processos,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Processos'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'assuntos',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
    
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>